sudo: false
language: node_js

cache: npm

node_js:
  - "10"

services:
  - docker

before_install:
  - docker build -t loopback .
  - docker run -p 127.0.0.1:80:4567 -d loopback:latest
  - docker ps -a

script: npm run test
install: npm install

branches:
  only:
    - master

before_deploy: docker login -u $DOCKER_USERNAME

deploy:
  provider: script
  script: docker tag loopback:latest mohamedragabessa/loopbacktravis:latest
    docker push mohamedragabessa/loopbacktravis:latest
  on:
    branch: master
    # loopback:latest
