sudo: false
language: node_js

cache: npm

node_js:
  - '10'

services:
 - docker

before_install:
  - docker build -t loopback .
  - docker run -p 127.0.0.1:3000 -d loopback
  - docker ps -a


script: - bundle exec rake test
install: npm install

branches:
  only:
    - master

# before_deploy:
deploy:
  provider: script
  script:
   docker tag mohamedragabessa/loopbacktravis:latest mohamedragabessa/loopbacktravis:latest
   docker push mohamedragabessa/loopbacktravis
  on:
    branch: master