sudo: false
language: node_js
node_js:
  - '10'

services:
 - docker

script: npm run test
install: npm install

branches:
  only:
    - master


deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push USER/REPO
  on:
    branch: master
