sudo: false
language: node_js

cache: npm

node_js:
  - '10'

services:
 - docker

script: npm run test
install: npm install

branches:
  only:
    - master

# before_deploy:
DOCKER_IMAGE_NAME=loopbacktravis
DOCKER_IMAGE_TAG=latest
deploy:
  provider: script
  script:
   docker push mohamedragabessa/$(DOCKER_IMAGE_NAME)
  on:
    branch: master

# after_deploy:

# export TRAVIS_WORKER_DOCKER_BINDS='/var/run/docker.sock:/var/run/docker.sock'
