sudo: false
language: node_js

cache: npm

node_js:
  - '10'

services:
 - docker

script: npm run test
install: npm install

branches:
  only:
    - master

# before_deploy:
deploy:
  provider: script
  script:
   docker build
   docker push mohamedragabessa/loopbacktravis
  on:
    branch: master