sudo: false
language: node_js
node_js:
  - '10'

  # services:
  # - docker

script: npm run test
install: npm install

branches:
  only:
    - master


  # deploy:
  # provider: script
  # script: bash docker_push
  # on:
  #   branch: master
